services:
  crawler:
    # build: .
    image: kantacky/gtfs-realtime-crawler:latest
    restart: always
    env_file:
      - ./.env.docker
    environment:
      DB_ROOT_CERT_PATH: /run/secrets/db_root_cert
      DB_CERT_PATH: /run/secrets/db_cert
      DB_KEY_PATH: /run/secrets/db_key
    secrets:
      - db_root_cert
      - db_cert
      - db_key

secrets:
  db_root_cert:
    file: ./cert/server-ca.pem
  db_cert:
    file: ./cert/client-cert.pem
  db_key:
    file: ./cert/client-key.pem
